# Generated by Django 4.1 on 2022-09-02 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Men',
            new_name='People',
        ),
    ]
